---
title: "PosgreSQL Cheatsheet"
author: "Marc Bañuls Tornero"
date: "11/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

For the examples we will use the tables A, B or C depending on the number of tables needed. The rows of table A will be persons with IDs, name, surname, age and email columns. The table B will be for cars with ID, model, brand and price as columns. To create randomized databases there is a webpage named Mockaroo, and with this I can test the different commandos without having to worry about sharing sensitive or personal content.
<<<<<<< HEAD


# Create table
CREATE TABLE A (
id BIGSERIAL NOTNULL PRIMARY KEY,
name VARCHAR(50) NOT NULL,
surname VARCHAR(50) NOT NULL,
age INT NOT NULL,
email VARCHAR(50)
);

CREATE TABLE B(
id BIGSERIAL NOT NULL PRIMARY KEY,
make VARCHAR(100) NOT NULL,
model VARCHAR(100) NOT NULL,
price NUMERIC (20, 2) NOT NULL
);

# Erase table
DROP TABLE A;

# Insert records
INSERT INTO A (
name,
surname,
age,
email
)
VALUES ('Marc', 'Banuls', 'MALE', '25','marc.banuls.96@gmail.com');


# Select all or some of the rows from a table
SELECT * FROM A;
SELECT name, age FROM A;

# Order alphabetically or numerically (ascending or descending optional argument)
SELECT * FROM A ORDER BY name, ASC;

# select only distinct variables from a column or row
SELECT DISTINCT age FROM A;

# select by a complete match in a column or several columns (AND)
SELECT * FROM A WHERE gender = 'MALE';
SELECT * FROM A WHERE gender = 'FEMALE' AND age = '22';

# select by match in a pattern

# Comparison
<> not equal
= equal

# Limit first numbers of rows shown
SELECT * FROM A LIMIT 10;

# Limit where starts showing rows
SELECT * FROM A OFFSET 5;

# Fetch specific rows
SELECT * FROM A FETCH FIRST 5 ROW ONLY;

# Filter rows with OR and WHERE
SELECT * FROM A WHERE age = '22', OR age = '25';

# Filter rows with multiple column patterns without OR
SELECT * FROM A WHERE age IN ('22', '25);

# Select a range of data (*only with dates? check*)
SELECT * FROM A WHERE age BETWEEN '22' AND '25';

# Select by similar pattern, with or without mayus filtering
SELECT * FROM A WHERE surname LIKE '%uls';
SELECT * FROM A WHERE surname ILIKE '%ULS';

# Group using a column
SELECT name FROM A GROUP BY age;

# Count repetitions of grouped table
SELECT name, COUNT(*) FROM A GROUP BY age;

# Select rows that have more or less counts grouped by a column
SELECT name, COUNT(\*) FROM A GROUP BY  age HAVING COUNT(\*) >10  ORDER BY age;

# Min max average sum
SELECT ROUND(AVG(age)) FROM A;
SELECT name, surname, MAX(age) FROM A;
SELECT SUM(age) FROM A;

# Create or change names of new columns and actual columns
SELECT age AS age_in_years, age * 365 AS age_in days;

# Select and change content of null rows
SELECT COALESCE (email, 'Without email') FROM A;

# If using a number in an operation gives null, use another number?
SELECT 5 / NULLIF(5,2);

# Timestamps and dates
SELECT NOW(); Gives full info of the time now
SELECT NOW()::DATE; Gives only the date of now
SELECT NOW()::TIME; Gives only the time we are at now
SELECT NOW() - INTERVAL '2 DAYS'; substracts two days at the date

# Extract concrete date
SELECT EXTRACT(DAY FROM NOW());

# Calculate age from two dates
SELECT AGE(NOW(), '02-02-1996') as exact_age FROM A;

# Remove constraint (primary keys for example)
ALTER TABLE A DROP CONSTRAINT A_pkey;

# Add constraint
ALTER TABLE A ADD PRIMARY KEY (id);
ALTER TABLE A ADD CONSTRAINT unique_email UNIQUE (email); also:
ALTER TABLE A ADD UNIQUE (email);

# Add check contents of column before inserting a row
ALTER TABLE A ADD CONSTRAINT gender_constraint CHECK (gender = 'FEMALE'::text OR gender = 'MALE')::text;

# Delete rows or 'records'
DELETE FROM A WHERE id = 1;

# Update rows or records
UPDATE A SET email = 'email2@gmail.com' WHERE id = 1;

# Prevent error messages on conflict or do something specific on conflict
INSERT INTO A (name, surname, age, email)
VALUES ('a', 'aa', 'MALE', '25', 'marc_testmail@gmail.com')
ON CONFLICT (email) DO NOTHING;
(this will result in not adding this record due to having same id as before)

INSERT INTO A (name, surname, age, email)
VALUES ('a', 'aa', 'MALE', '25', 'marc_testmail@gmail.com')
ON CONFLICT (email) DO UPDATE SET email = EXCLUDED.email;

# Relational databases
To have relational databases we need a column with the id of one table on another table, in our case:

CREATE TABLE A (
id BIGSERIAL NOTNULL PRIMARY KEY,
name VARCHAR(50) NOT NULL,
surname VARCHAR(50) NOT NULL,
age INT NOT NULL,
email VARCHAR(50)
*car_id BIGINT REFERENCES car (id)*,
UNIQUE(car_id)
);

CREATE TABLE B (
id BIGSERIAL NOT NULL PRIMARY KEY,
make VARCHAR(100) NOT NULL,
model VARCHAR(100) NOT NULL,
price NUMERIC (20, 2) NOT NULL
);

# Update relational table with foreign key
UPDATE A car_id = 2 WHERE id = 1;

# Inner join: only what is related between two tables
SELECT * FROM A
JOIN B ON A.B.id = car.id

# Left join: select everything of A and only things in B related to A
SELECT * FROM A
LEFT JOIN B ON B.id = A.B.id;

# Export results of query to csv file
\copy (SELECT * FROM A
JOIN B ON A.B.id = car.id )
TO '/path/of/directory/results.csv'
DELIMITER ',' CSV HEADER;

# change or set sequence
ALTER SEQUENCE A_id_seq RESTART WITH 10;

# Extensions
SELECT * FROM pg_available_extension






































